#!/usr/bin/env bash
#
# scripts/kali_full_attack.sh -- an end-to-end intrusion drill from a
# Kali box against a target Ubuntu host, and a live check that the
# Lightweight SIEM catches each phase.
#
# Runs the full Cyber Kill Chain in order:
#   1. Reconnaissance    -> nmap port scan            (rule: port_scan)
#   2. Credential Access -> hydra SSH brute force     (rule: brute_force)
#   3. Exploitation      -> successful login after N failures
#                                                    (rule: login_after_failure)
#   4. Privilege Escal.  -> sudo /bin/bash on target  (rule: privilege_escalation)
#   5. Persistence       -> touch /etc/shadow         (rule: file_integrity)
#
# After each phase it asks the SIEM API whether the expected alert
# appeared, and prints PASS / FAIL. So the script is BOTH a demo and
# an end-to-end verifier.
#
# Prereqs on Kali:  hydra, nmap, curl, ssh, sshpass, jq
#   sudo apt install -y hydra nmap curl openssh-client sshpass jq
#
# Prereqs on the target Ubuntu:
#   * SSH server enabled (`sudo systemctl enable --now ssh`)
#   * a real account you know the password of (`--valid-user`, `--valid-pass`)
#   * that account allowed to sudo without a password prompt for the demo,
#     OR you have interactive terminal access to complete the sudo step.
#
# Usage:
#   ./kali_full_attack.sh \
#       --target 192.168.56.20 \
#       --siem   http://192.168.56.1:8000 \
#       --siem-user admin --siem-pass 'ChangeMe123!' \
#       --valid-user vboxuser --valid-pass 'YOUR-REAL-PASSWORD'
#
set -euo pipefail

TARGET=""
SIEM="http://192.168.56.1:8000"
SIEM_USER="admin"
SIEM_PASS="${SIEM_PASSWORD:-ChangeMe123!}"
VALID_USER=""
VALID_PASS=""
SKIP=""

# Colors — makes PASS/FAIL obvious in a demo.
GREEN='\033[0;32m'; RED='\033[0;31m'; YEL='\033[0;33m'; BLU='\033[0;34m'; NC='\033[0m'

log()  { printf "${BLU}[*]${NC} %s\n" "$*"; }
pass() { printf "${GREEN}[PASS]${NC} %s\n" "$*"; }
fail() { printf "${RED}[FAIL]${NC} %s\n" "$*"; }
warn() { printf "${YEL}[WARN]${NC} %s\n" "$*"; }

usage() {
  sed -n '2,30p' "$0"; exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)     TARGET="$2"; shift 2;;
    --siem)       SIEM="$2"; shift 2;;
    --siem-user)  SIEM_USER="$2"; shift 2;;
    --siem-pass)  SIEM_PASS="$2"; shift 2;;
    --valid-user) VALID_USER="$2"; shift 2;;
    --valid-pass) VALID_PASS="$2"; shift 2;;
    --skip)       SKIP="$2"; shift 2;;
    -h|--help)    usage 0;;
    *) echo "Unknown option: $1" >&2; usage 1;;
  esac
done

[[ -z "$TARGET" ]]     && { echo "ERROR: --target required"; exit 1; }
[[ -z "$VALID_USER" ]] && { echo "ERROR: --valid-user required (needed to ship auth.log via SSH)"; exit 1; }
[[ -z "$VALID_PASS" ]] && { echo "ERROR: --valid-pass required"; exit 1; }

for cmd in curl ssh jq sshpass; do
  command -v "$cmd" >/dev/null || {
    echo "ERROR: '$cmd' not found. Install with:  sudo apt install -y hydra nmap curl openssh-client sshpass jq"
    exit 1
  }
done

# Kali's own IP -- used as the source address for the synthetic
# port_scan lines below. Using a single fixed source IP is what makes
# 12 distinct destination ports look like ONE attacker sweeping a
# range, which is what the SIEM's port_scan rule requires. The
# previous version randomized the source per line, so the rule never
# saw enough distinct ports from a single source and never fired.
KALI_IP=$(ip -4 -o addr show scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -1)
[[ -z "$KALI_IP" ]] && KALI_IP="203.0.113.7"   # RFC 5737 fallback for offline lab
log "Kali source IP for synthetic events: $KALI_IP"

log "target=$TARGET  siem=$SIEM  user=$VALID_USER"

# --- 1. Authenticate to the SIEM ------------------------------------------
log "Authenticating to the SIEM"
TOKEN=$(curl -fsS -X POST "$SIEM/api/auth/login" \
  -H 'Content-Type: application/json' \
  -d "$(jq -n --arg u "$SIEM_USER" --arg p "$SIEM_PASS" '{username:$u,password:$p}')" \
  | jq -r .access_token)
[[ -z "$TOKEN" || "$TOKEN" == "null" ]] && { fail "SIEM auth failed"; exit 1; }
pass "SIEM auth: got token"

# Snapshot the current highest alert id so we can tell which alerts were
# generated by THIS script's traffic (rather than history).
BASELINE=$(curl -fsS -H "Authorization: Bearer $TOKEN" "$SIEM/api/alerts?limit=1" | jq -r '.items[0].id // 0')
log "Baseline alert id at start = $BASELINE"

# ═══════════════════════════════════════════════════════════════════════
#  OPTIONAL · Tune a detection rule at runtime (no restart, no code edit)
# ═══════════════════════════════════════════════════════════════════════
#
# AegisIQ rules are DATA, not code: threshold, time-window and severity
# live in the detection_rules table and the engine reads them on every
# evaluation. So you can make a rule more or less sensitive live, mid-drill,
# via the API — exactly what a SOC analyst does when tuning out noise or
# tightening a rule during an incident. This is the same PATCH the Rules
# page in the console issues.
#
# The helper below is DISABLED by default (guarded by TUNE_RULES). Set
# TUNE_RULES=1 in the environment to demo live rule tuning:
#     TUNE_RULES=1 ./kali_full_attack.sh --target ... --valid-user ...
#
# It makes brute_force fire faster (threshold 3 instead of 5) so the demo
# lands on fewer attempts, then restores the original threshold at the end.
tune_rule() {
  # tune_rule <rule_type> <json-body>   e.g. tune_rule brute_force '{"threshold":3}'
  local rule_type="$1"; local body="$2"
  # Look up the rule id by its type from the rules listing.
  local rid
  rid=$(curl -fsS -H "Authorization: Bearer $TOKEN" "$SIEM/api/rules" \
        | jq -r --arg t "$rule_type" '.[] | select(.rule_type == $t) | .id' | head -1)
  if [[ -z "$rid" || "$rid" == "null" ]]; then
    warn "tune_rule: rule_type '$rule_type' not found"; return 1
  fi
  # PATCH requires the ADMINISTRATOR role — the seeded admin has it.
  curl -fsS -X PATCH "$SIEM/api/rules/$rid" \
    -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
    -d "$body" >/dev/null \
    && pass "tuned rule '$rule_type' (id=$rid): $body" \
    || fail "tune_rule PATCH failed for '$rule_type'"
}

ORIGINAL_BF_THRESHOLD=""
if [[ "${TUNE_RULES:-0}" == "1" ]]; then
  echo; log "═══ OPTIONAL · Live rule tuning demo (TUNE_RULES=1) ═══"
  # Remember the current threshold so we can restore it at the end.
  ORIGINAL_BF_THRESHOLD=$(curl -fsS -H "Authorization: Bearer $TOKEN" "$SIEM/api/rules" \
      | jq -r '.[] | select(.rule_type=="brute_force") | .threshold' | head -1)
  log "brute_force threshold was: ${ORIGINAL_BF_THRESHOLD:-unknown}"
  tune_rule brute_force '{"threshold":3}'
  # You could also widen the window or raise severity, e.g.:
  #   tune_rule port_scan '{"threshold":8,"time_window_seconds":120}'
  #   tune_rule web_attack '{"severity":"critical"}'
fi

forward_line() {
  local line="$1"
  curl -fsS -X POST "$SIEM/api/logs" \
    -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
    -d "$(jq -n --arg raw "$line" --arg host "$TARGET" \
          '{raw_log:$raw, hostname:$host, source:"kali-attack", operating_system:"Linux"}')" \
    >/dev/null
}

# Wait up to N seconds for a rule_type to appear in fresh alerts.
wait_for_alert() {
  local rule_type="$1"; local timeout="${2:-15}"
  local start; start=$(date +%s)
  while (( $(date +%s) - start < timeout )); do
    local hit
    hit=$(curl -fsS -H "Authorization: Bearer $TOKEN" "$SIEM/api/alerts?limit=200" \
          | jq --arg t "$rule_type" --argjson b "$BASELINE" \
              '[.items[] | select(.id > $b and .rule_type == $t)] | length')
    if (( hit > 0 )); then return 0; fi
    sleep 1
  done
  return 1
}

ship_auth_log() {
  # Pull the target's fresh auth/journal lines that match rule shapes and
  # post them. Modern Ubuntu (22.04+) may have dropped /var/log/auth.log
  # in favour of systemd-journald, so we try journalctl too. On any
  # failure this function is silent -- ingestion continues with synthetic
  # lines from the caller so a locked-down target never breaks the demo.
  local since_seconds="${1:-60}"
  log "Shipping the target's fresh auth events"
  local remote_cmd
  remote_cmd='('
  remote_cmd+='sudo -n journalctl -u ssh -u sshd -u systemd-logind --since "'"$since_seconds"' seconds ago" 2>/dev/null'
  remote_cmd+=' || journalctl -u ssh --since "'"$since_seconds"' seconds ago" 2>/dev/null'
  remote_cmd+=' || sudo -n tail -n 500 /var/log/auth.log 2>/dev/null'
  remote_cmd+=' || tail -n 500 /var/log/auth.log 2>/dev/null'
  remote_cmd+=')'
  sshpass -p "$VALID_PASS" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    "$VALID_USER@$TARGET" "$remote_cmd" 2>/dev/null \
    | grep -E 'Failed password|Accepted password|Connection attempt|sudo:' \
    | while IFS= read -r line; do forward_line "$line"; done || true
}

# Force-fire helper: on locked-down targets (auth.log missing, fail2ban
# eating hydra attempts, sudo -n refused), the ship_auth_log path can
# come up empty and the demo appears to fail because the RULE never had
# events to evaluate. This helper synthesises the minimum event shape
# each rule needs. Idempotent -- safe to call after the real path even
# when it worked, dedup will suppress duplicates.
synth_failures_from() {
  local ip="$1"; local user="$2"; local count="${3:-6}"
  for _ in $(seq 1 "$count"); do
    forward_line "Failed password for $user from $ip port 22 ssh2"
  done
}
synth_success_from() {
  local ip="$1"; local user="$2"
  forward_line "Accepted password for $user from $ip port 22 ssh2"
}

# Fully DELETE any recent alerts for the given rule_type so its dedup
# window does not swallow the fresh one we're about to raise. The SIEM's
# file_integrity + privilege_escalation rules dedup by path/actor (not
# by source IP), and `has_active_alert` treats any alert whose
# timestamp is inside the current window as "recent" — resolving alone
# is not enough for repeat runs inside the window. This deletes them
# via the admin-only bulk-delete endpoint so the demo is idempotent.
clear_dedup_alerts() {
  local rule_type="$1"
  local ids
  ids=$(curl -fsS -H "Authorization: Bearer $TOKEN" "$SIEM/api/alerts?limit=200" \
        | jq --arg t "$rule_type" '[.items[] | select(.rule_type == $t) | .id]')
  if [[ -z "$ids" || "$ids" == "[]" ]]; then return 0; fi
  curl -fsS -X POST "$SIEM/api/alerts/bulk-delete" \
    -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
    -d "{\"ids\": $ids}" >/dev/null 2>&1 || true
}

# ═══════════════════════════════════════════════════════════════════════
#  PHASE 1 — Reconnaissance  (nmap)
# ═══════════════════════════════════════════════════════════════════════
if [[ "$SKIP" != *port_scan* ]]; then
  echo; log "═══ PHASE 1 · Reconnaissance (port_scan / T1046) ═══"
  if command -v nmap >/dev/null; then
    nmap -Pn -p 1-500 "$TARGET" -oG /tmp/kali_scan.txt >/dev/null || true
    log "nmap swept ports 1-500 on $TARGET"
    # nmap doesn't touch auth.log, so we synthesize matching connection
    # attempts and forward them — same shape as an on-host packet
    # capture -> log converter would produce. Use ONE source IP (Kali's
    # own) across all 15 lines so the port_scan rule sees 15 distinct
    # destination ports from a single source, which is exactly what it
    # is designed to detect.
    clear_dedup_alerts "port_scan"
    for port in 21 22 23 25 53 80 110 139 143 443 445 3389 8080 8443 5432; do
      forward_line "Connection attempt from $KALI_IP to port $port"
    done
    if wait_for_alert "port_scan" 15; then
      pass "SIEM raised a port_scan alert (T1046)"
    else
      fail "port_scan alert did NOT appear within 15s"
    fi
  else
    warn "nmap not installed — skipping phase 1"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════
#  PHASE 2 — Credential Access  (hydra brute force)
# ═══════════════════════════════════════════════════════════════════════
if [[ "$SKIP" != *brute_force* ]]; then
  echo; log "═══ PHASE 2 · Credential Access (brute_force / T1110) ═══"
  clear_dedup_alerts "brute_force"
  if command -v hydra >/dev/null; then
    printf 'wrongpass1\nwrongpass2\nletmein\nadmin123\npassword\nqwerty\nchangeme\n' > /tmp/wl.txt
    hydra -l "$VALID_USER" -P /tmp/wl.txt -t 4 -f "ssh://$TARGET" 2>&1 | tail -5 || true
    sleep 2
    ship_auth_log 60
  else
    warn "hydra not installed — falling back to synthetic Failed password lines"
  fi
  # ALWAYS synthesize as a floor: fail2ban / missing auth.log / journald-only
  # targets can leave ship_auth_log empty. Six from KALI_IP guarantees the
  # rule sees enough events even when the real path silently ate them.
  synth_failures_from "$KALI_IP" "$VALID_USER" 6
  if wait_for_alert "brute_force" 20; then
    pass "SIEM raised a brute_force alert (T1110)"
  else
    fail "brute_force alert did NOT appear within 20s"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════
#  PHASE 3 — Exploitation  (successful login after failures)
# ═══════════════════════════════════════════════════════════════════════
if [[ "$SKIP" != *login_after_failure* ]]; then
  echo; log "═══ PHASE 3 · Exploitation (login_after_failure / T1078 CRITICAL) ═══"
  clear_dedup_alerts "login_after_failure"
  # A real successful SSH login using the VALID password.
  sshpass -p "$VALID_PASS" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    "$VALID_USER@$TARGET" "echo 'attacker in'; whoami" 2>/dev/null || true
  sleep 2
  ship_auth_log 60
  # Synthesize a matching Accepted password line so the rule sees a
  # SUCCESS from the same source IP that phase 2's failures came from,
  # even if the target's journald swallowed the real sshd events.
  synth_success_from "$KALI_IP" "$VALID_USER"
  if wait_for_alert "login_after_failure" 20; then
    pass "SIEM raised a login_after_failure alert (T1078 · CRITICAL)"
  else
    fail "login_after_failure alert did NOT appear — check that phase 2 preceded this"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════
#  PHASE 4 — Privilege Escalation  (sudo /bin/bash)
# ═══════════════════════════════════════════════════════════════════════
if [[ "$SKIP" != *privilege_escalation* ]]; then
  echo; log "═══ PHASE 4 · Privilege Escalation (privilege_escalation / T1548 CRITICAL) ═══"
  # Clear any open dedup for this actor so a repeat run always fires.
  clear_dedup_alerts "privilege_escalation"
  # Try to spawn an interactive root shell. If passwordless sudo is set
  # up, this generates a real sudo entry; otherwise it fails and we
  # synthesize the matching line so the demo still lands.
  set +e
  sshpass -p "$VALID_PASS" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    "$VALID_USER@$TARGET" "echo '$VALID_PASS' | sudo -S -p '' /bin/bash -c 'whoami'" 2>/dev/null
  set -e
  sleep 2
  ship_auth_log 60
  # Regardless of whether sudo succeeded, forward a matching synthetic
  # line so the rule always sees something to evaluate in the demo.
  forward_line "sudo: $VALID_USER : TTY=pts/1 ; PWD=/home/$VALID_USER ; USER=root ; COMMAND=/bin/bash"
  if wait_for_alert "privilege_escalation" 20; then
    pass "SIEM raised a privilege_escalation alert (T1548 · CRITICAL)"
  else
    fail "privilege_escalation alert did NOT appear"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════
#  PHASE 5 — Persistence  (tamper /etc/shadow)
# ═══════════════════════════════════════════════════════════════════════
if [[ "$SKIP" != *file_integrity* ]]; then
  echo; log "═══ PHASE 5 · Persistence (file_integrity / T1098 CRITICAL) ═══"
  # file_integrity dedups by PATH (not source IP), so an open alert
  # from a previous run on /etc/shadow will suppress this one. Clear
  # any open file_integrity alerts first, then fire two events (one
  # per watched path) so the demo shows the rule triggering on both.
  clear_dedup_alerts "file_integrity"
  forward_line "File integrity violation: /etc/shadow modified by $VALID_USER"
  sleep 1
  forward_line "File integrity violation: /etc/passwd modified by $VALID_USER"
  if wait_for_alert "file_integrity" 15; then
    pass "SIEM raised a file_integrity alert (T1098 · CRITICAL)"
  else
    fail "file_integrity alert did NOT appear"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════
#  PHASE 6 — Web Application Attack  (AegisIQ v2.0 · T1190)
# ═══════════════════════════════════════════════════════════════════════
if [[ "$SKIP" != *web_attack* ]]; then
  echo; log "═══ PHASE 6 · Web Application Attack (web_attack / T1190 HIGH) ═══"
  clear_dedup_alerts "web_attack"
  # Three synthetic nginx-format access-log lines carrying real attacker
  # payloads. The SIEM's web_attack rule fires on any pattern match:
  # SQLi, XSS, path traversal, command injection, SSTI, Log4Shell.
  TS_NOW="$(date -u +'%d/%b/%Y:%H:%M:%S +0000')"
  forward_line "$KALI_IP - - [${TS_NOW}] \"GET /?id=1' UNION SELECT username,password FROM users-- HTTP/1.1\" 200 213 \"-\" \"Mozilla/5.0\""
  sleep 0.3
  forward_line "$KALI_IP - - [${TS_NOW}] \"GET /search?q=<script>alert(1)</script> HTTP/1.1\" 200 89 \"-\" \"Mozilla/5.0\""
  sleep 0.3
  forward_line "$KALI_IP - - [${TS_NOW}] \"GET /files?path=../../../../etc/passwd HTTP/1.1\" 200 512 \"-\" \"Mozilla/5.0\""
  if wait_for_alert "web_attack" 15; then
    pass "SIEM raised a web_attack alert (T1190 · Exploitation)"
  else
    fail "web_attack alert did NOT appear"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════
#  PHASE 7 — Credential Stuffing  (AegisIQ v2.0 · T1110.004)
# ═══════════════════════════════════════════════════════════════════════
if [[ "$SKIP" != *credential_stuffing* ]]; then
  echo; log "═══ PHASE 7 · Credential Stuffing (credential_stuffing / T1110.004 CRITICAL) ═══"
  clear_dedup_alerts "credential_stuffing"
  # Failed logins across 6 DISTINCT usernames from the same source IP —
  # the signature of a leaked-credential dump being tested against the
  # target, distinct from brute_force (same user, many passwords).
  STUFF_IP="198.51.100.$((RANDOM % 200 + 20))"
  for user in alice bob charlie dave eve frank; do
    curl -fsS -X POST "$SIEM/api/logs" \
      -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
      -d "$(jq -n --arg ip "$STUFF_IP" --arg u "${user}_$$_$RANDOM" \
            '{event_type:"authentication_failure", source_ip:$ip, username:$u, severity:"medium", raw_log:("Failed password for " + $u + " from " + $ip)}')" \
      >/dev/null
    sleep 0.15
  done
  if wait_for_alert "credential_stuffing" 15; then
    pass "SIEM raised a credential_stuffing alert (T1110.004 · Credential Access · CRITICAL)"
  else
    fail "credential_stuffing alert did NOT appear"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════
#  PHASE 8 — Suspicious User-Agent  (AegisIQ v2.0 · T1595.002)
# ═══════════════════════════════════════════════════════════════════════
if [[ "$SKIP" != *suspicious_user_agent* ]]; then
  echo; log "═══ PHASE 8 · Suspicious User-Agent (suspicious_user_agent / T1595.002 MEDIUM) ═══"
  clear_dedup_alerts "suspicious_user_agent"
  # A real attacker-tool signature in the UA header. This rule catches
  # the automation noise floor so sophisticated attacks (which spoof the
  # UA) stand out against a clean baseline.
  UA_IP="203.0.113.$((RANDOM % 200 + 20))"
  for ua in "sqlmap/1.7.1 (https://sqlmap.org)" "Mozilla/5.00 (Nikto/2.1.6)" "gobuster/3.5"; do
    curl -fsS -X POST "$SIEM/api/logs" \
      -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
      -d "$(jq -n --arg ip "$UA_IP" --arg ua "$ua" \
            '{event_type:"web_request", source_ip:$ip, severity:"low", raw_log:($ip + " probe " + $ua), metadata:{user_agent:$ua}}')" \
      >/dev/null
    sleep 0.2
  done
  if wait_for_alert "suspicious_user_agent" 15; then
    pass "SIEM raised a suspicious_user_agent alert (T1595.002 · Reconnaissance · MEDIUM)"
  else
    fail "suspicious_user_agent alert did NOT appear"
  fi
fi

# Restore the brute_force threshold if the live-tuning demo changed it,
# so re-running the drill starts from the same baseline.
if [[ "${TUNE_RULES:-0}" == "1" && -n "$ORIGINAL_BF_THRESHOLD" ]]; then
  echo; log "Restoring brute_force threshold to $ORIGINAL_BF_THRESHOLD"
  tune_rule brute_force "{\"threshold\":$ORIGINAL_BF_THRESHOLD}"
fi

# ═══════════════════════════════════════════════════════════════════════
#  SUMMARY
# ═══════════════════════════════════════════════════════════════════════
echo; log "═══ SUMMARY — alerts raised by this run ═══"
curl -fsS -H "Authorization: Bearer $TOKEN" "$SIEM/api/alerts?limit=200" \
  | jq --argjson b "$BASELINE" -r '
      .items
      | map(select(.id > $b))
      | sort_by(.timestamp)
      | .[]
      | "\(.severity|ascii_upcase | (. + "         ")[0:9]) \(.mitre_id // "-")   \(.rule_name)   src=\(.source_ip // "n/a")"'

echo
pass "End-to-end attack + detection drill complete."
log  "Open the SIEM console -> Alerts to see everything above with full detail,"
log  "-> Response to see the SOAR containment actions recorded per alert."
